stages:
    - build
    - test 

backend_build:
    image: python:3.7
    stage: build
    script:
        - echo "Building"
        - pip install -r backend/requirements.txt -t backend/api/

backend_linting:
    image: python:3.7
    stage: test
    needs: [backend_build]
    script:
        - echo "Testing"
        - pip install -r backend/requirements.txt
        - pip install nose2
        - nose2 -v 
        - pip install flake8
        - flake8 backend/api
        - pip install flask-lint
        - pip run flask-lint
    only: 
        - branches
    allow_failure: true

frontend_build:
    image: node:latest
    stage: build
    script:
        - cd frontend
        - npm install
    
frontend_linting:
    
    image: node:latest
    stage: test
    needs: [frontend_build]
    script:
        - cd frontend
        - npm install eslint 
        - npx eslint --init
        - npx eslint src/**/*.js
        - npx eslint src/**/*.jsx # Add path to files where linter have to run
    allow_failure: true

#f_test:e2e: auskomentiere wenn ein extra test selber gebaut ist
#    before_script:
#        - cd frontend
#    stage: test
#    image: cypress/browsers:chrome69
#    dependencies:
#        - f_install
#        - f_build
#    script:
#        - npm run e2e:ci
#    artifacts:
#        paths:
#            - cypress/screenshots
#            - cypres/videos
#        expire_in: 1 day
#Test-Frontend-to-Wlog:
#Deploy-Frontend-to-Wlog: