stages:
    - install
    - build
    - test 
Build-Backend-to-Wlog:
    image: python:3.7
    stage: build
    script:
        - echo "Building"
        - pip install -r api/requirements.txt -t api/
    artifacts:
        paths:
            - api/
            - test_b/
Test-Backend-to-Wlog:
    image: python:3.7
    stage: test
    script:
        - echo "Testing"
        - pip install -r api/requirements.txt
        #- pip install nose2
        #- nose2 -v 
        - pip install flake8
        - flake8 api/app.py
        - pip install flask-lint
        - pip run flask-lint
    only: 
        - branches
#Deploy-Backend-to-Wlog:
f_install:
    stage: install
    script:
        - npm install
    artifacts:
        name: "artifacts"
        untracked: true
        expire_in: 30 mins
        paths:
            - .npm/
            - node_modules/
f_build:
    stage: build
    script:
        - CI=false npm run build
    artifacts:
        paths:
            - build
        expire_in: 30 mins
    dependencies:
        - f_install
f_linting:
    stage: test
    script:
        -npm run lint
f_test:e2e:
    stage: test
    image: cypress/browsers:chrome69
    dependencies:
        - f_install
        - f_build
    script:
        - npm run e2e:ci
    artifacts:
        paths:
            - cypress/screenshots
            - cypres/videos
        expire_in: 1 day
#Test-Frontend-to-Wlog:
#Deploy-Frontend-to-Wlog: