version: "3"

services:
  api:
    build: ./backend
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=api
      - FLASK_DEBUG=1
    depends_on:
      - mariadb

  frontend:
    build: ./frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules/
    stdin_open: true
    links:
      - api

  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: iamroot
      MYSQL_DATABASE: wlog
      MYSQL_USER: admin
      MYSQL_PASSWORD: wlog2020

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
